create table if not exists public.api_cache (
    cache_key text primary key,
    cache_type text not null,
    response_data jsonb not null,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists api_cache_expiry_idx on public.api_cache (expires_at);

create table if not exists public.issue_reports (
    id bigint generated by default as identity primary key,
    category text not null default 'routing',
    description text not null,
    journey_context jsonb,
    contact_email text,
    status text not null default 'new',
    created_at timestamptz not null default now()
);

alter table public.api_cache enable row level security;
alter table public.issue_reports enable row level security;

-- No public policies: only the server-side secret key accesses these tables.
